import Head from "next/head";
import Link from "next/link";

import styles from "./index.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>ShipSpeed</title>
        <meta name="description" content="Generated by create-shipspeed" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            Create <span className={styles.pinkSpan}>ShipSpeed</span> App
          </h1>
          <div className={styles.cardRow}>
            <Link
              className={styles.card}
              href="https://github.com/rbnog/shipspeed#first-steps"
              target="_blank"
            >
              <h3 className={styles.cardTitle}>First Steps →</h3>
              <div className={styles.cardText}>
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className={styles.card}
              href="https://github.com/rbnog/shipspeed"
              target="_blank"
            >
              <h3 className={styles.cardTitle}>Documentation →</h3>
              <div className={styles.cardText}>
                Learn more about ShipSpeed, the libraries it uses, and how to
                deploy it.
              </div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
