import scrollbar from "tailwind-scrollbar";
import { type Config } from "tailwindcss";

export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  darkMode: "selector",
  theme: {
    extend: {
      colors: {
        default: "rgb(var(--color-default) / <alpha-value>)",
        neutral: "rgb(var(--color-neutral) / <alpha-value>)",
        primary: "rgb(var(--color-primary) / <alpha-value>)",
        secondary: "rgb(var(--color-secondary) / <alpha-value>)",
        accent: "rgb(var(--color-accent) / <alpha-value>)",
        warning: "rgb(var(--color-warning) / <alpha-value>)",
        error: "rgb(var(--color-error) / <alpha-value>)",
        success: "rgb(var(--color-success) / <alpha-value>)",
        info: "rgb(var(--color-info) / <alpha-value>)",

        "ss-gray-50": "#fafafa",
        "ss-gray-100": "#f4f4f5",
        "ss-gray-200": "#e4e4e7",
        "ss-gray-300": "#d4d4d8",
        "ss-gray-400": "#a1a1aa",
        "ss-gray-500": "#71717a",
        "ss-gray-600": "#52525b",
        "ss-gray-700": "#3f3f46",
        "ss-gray-800": "#27272a",
        "ss-gray-900": "#18181b",
        "ss-gray-1000": "#09090b",

        /* Muted purple accent aligned with B&W monotone palette */
        "ss-purple-50": "#fafafa",
        "ss-purple-100": "#f4f4f5",
        "ss-purple-200": "#e4e4e7",
        "ss-purple-300": "#d4d4d8",
        "ss-purple-400": "#a1a1aa",
        "ss-purple-500": "#71717a",
        "ss-purple-600": "#52525b",
        "ss-purple-700": "#3f3f46",
        "ss-purple-800": "#27272a",
        "ss-purple-900": "#18181b",
      },
      animation: {
        draw: "draw 2s linear normal",
      },
    },
    keyframes: {
      draw: {
        to: { strokeDashoffset: "200" },
      },
    },
    fontFamily: {
      sans: [
        '"InterVariable"',
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        '"Segoe UI"',
        "Roboto",
        '"Helvetica Neue"',
        "Arial",
        '"Noto Sans"',
        "sans-serif",
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
      serif: ["ui-serif", "Georgia"],
      mono: [
        '"JetBrains Mono"',
        "monospace",
        "ui-monospace",
        "Menlo",
        "Monaco",
        '"Cascadia Mono"',
        '"Segoe UI Mono"',
        '"Roboto Mono"',
        '"Oxygen Mono"',
        '"Ubuntu Monospace"',
        '"Source Code Pro"',
        '"Fira Mono"',
        '"Droid Sans Mono"',
        '"Courier New"',
      ],
    },
  },
  plugins: [scrollbar({ nocompatible: true })],
} satisfies Config;
